server:
  port: 10300
  cache:
    type: redis
#静态资源路径
static:
  file: "file:/usr/lottery/web/upload/"
#  file: "file:D:/ideaproject2/ball_web_new/out/artifacts/ball_web_new_jar/upload/"
spring:
  #设置单个文件的大小，默认1MB
  servlet:
    multipart:
      #单个文件大小
      max-file-size: 20MB
      #一次请求总大小
      max-request-size: 50MB
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
  datasource:
    druid:
      url: "jdbc:mysql://127.0.0.1:3306/lottery?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
      username: "root"
      password: "123123"
#      url: "jdbc:mysql://47.242.171.53:3306/lottery?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8"
#      username: "lottery"
#      password: "86YKydnLZ7LLN58A"
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池配置
      min-idle: 1
      initial-size: 20
      max-active: 2000
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 20000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      remove-abandoned: true
      remove-abandoned-timeout: 120
      log-abandoned: true
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #sql查询超时时间
      query-timeout: 160
      #监控
      filter:
        wall:
          enabled: true
          config:
            multi-statement-allow: true
#          keep-alive: true
      max-pool-prepared-statement-per-connection-size: 50
  redis:
    database: 5
    #TODO 配置redis
    host: 127.0.0.1
#    host: 192.168.101.66
#    password: 123123
    port: 6379
    timeout: 3000ms
  #
logging:
  level:
    root: info
    com.oxo.lottery.mapper: debug
    org.apache.http.client.protocol: error
some-comfig:
  #资讯交易-接口token
  dealToken: 'eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJmNzdiNWQwOS1mODY4LTRiOTItOTNlNC0wNzQxYWJhNGMxNmYiLCJleHAiOjE2OTQ1OTM4NjksImlhdCI6MTY5MjAwMTg2OSwic2lkIjoiNTBhMWQwMDItMjMzZS00YWYzLWE2MDgtODQzZTA4NmViMWI5IiwidHlwIjoiYWNjZXNzIiwiaWQiOiJhZGY0NDNlNy1jODhmLTQxMTgtODEwZi00ZjVjZDc5YzFiYTciLCJwdmQiOiJyZWd1bGFyIiwicHJ0IjoiMjMwOCIsImF0dHJpYnV0ZXMiOnsid2FsbGV0X2lkIjoiY2E0MDljYjVmOGJlNGFhNjg5ZmQxZGFmNmZkOTIzNDU3NGNmZDk4NThkOWM0NDNjYTgxZTViNzZhN2RjNGJjMCIsInNhZ2Ffd2FsbGV0X2FkZHJlc3MiOiIweDE3MDRhOTE4ZkUzQjM1YzgxZDJGYWZFMENFMDI2OTA1QkU2MzhmRkQiLCJhY2NvdW50X2lkIjoiNmRjODMyZDMtMmFjNC00MmEyLThmMTctZGU4ZjFjMGI4MjVlIn19.6AWq-ur1EQNUtuHzF2fGFt0O8pf_5_N-nVGP8TpwDzKNKNVuAAZJCUOWo4wSdIqMYhMszJqMa-mw0ulwMUQsqA'
  #资讯赛事-接口token
  gameApiToken: 'gjXbar21DG5re5QIeKxtq-P5GapAkooyd3YT3iH6cQoCsbdVxhY'
  #服务器名,随意写,每台不一样,负载里面测试是否都有请求到
  server-name: s1
  #是否为主服,加了才是主,不加默认非主
  main-server: 1
  day-back: 23
  server-url: 'http://127.0.0.2:10100/'
  api-key: ""
  #开启在线API
  api-bookmaker: 1
  #测试模式
  api-switch: 0
  #小数位数
  accuracy: 2

  #前端访问地址，拼接邀请码，不需要了
#  invitation-url: "http://localhost:9527/?code="
#    - 72
#    - 269
#    - 673
# wy011620.
# 短信平台 http://www.quanqiusms.com/
#
#

#EtSee4FGB2Z3Lfaa
#https://192.168.101.66:7800/505de289
#hzxd4lsj
#1b10f4e1


#https://192.168.101.66:7800/1818aafb
#username: 9t9iwwfu
  #password: 2be32004